library(SingleR)
library(celldex)
refdata <- celldex::HumanPrimaryCellAtlasData()
cellpred <- SingleR(test = cancercombined@assays$RNA@data, ref = refdata, labels = refdata$label.fine, clusters = cancercombined@active.ident, assay.type.test = "logcounts", assay.type.ref = "logcounts")
celltype = data.frame(ClusterID=rownames(cellpred), 
                      celltype=cellpred$labels, 
                      stringsAsFactors = F) 
cancercombined@meta.data$singleR=celltype[match(cancercombined@active.ident,celltype$ClusterID),'celltype']
markers <- FindAllMarkers(cancercombined, only.pos = TRUE)
cancercombined<-RenameIdents(cancercombined,"0"="T cell")
cancercombined<-RenameIdents(cancercombined,"8"="T cell")
cancercombined<-RenameIdents(cancercombined,"1"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"2"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"3"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"5"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"6"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"7"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"9"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"11"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"18"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"20"="Epithelial")
cancercombined<-RenameIdents(cancercombined,"10"="Stromal")
cancercombined<-RenameIdents(cancercombined,"22"="Stromal")
cancercombined<-RenameIdents(cancercombined,"12"="Endothelial")
cancercombined<-RenameIdents(cancercombined,"4"="Macrophage")
cancercombined<-RenameIdents(cancercombined,"17"="Mast cell")
cancercombined<-RenameIdents(cancercombined,"21"="T cell")
cancercombined<-RenameIdents(cancercombined,"19"="B cell")
cancercombined<-RenameIdents(cancercombined,"15"="B cell")
cancercombined<-RenameIdents(cancercombined,"14"="Monocyte")
cancercombined<-RenameIdents(cancercombined,"13"="Dendritic cell")
cancercombined<-RenameIdents(cancercombined,"16"="Dendritic cell")
library(ggplot2)
DimPlot(cancercombined,label = T,label.size = 8)->p
ggsave("umap.jpg",p,width = 10,height = 6,dpi = 300)
DoHeatmap(cancercombined,features = c("HLA-DPB1","FCN1","CD79A","JCHAIN","CD3D","GATA2","CD68","CD163","FLT1","COL1A1","COL1A2","KRT8","KRT16","KRT18"),label=F)->p
ggsave("umap.jpg",p,width = 10,height = 6,dpi = 300)